services:
  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "3000:3000"
    volumes:
      - ./APIS/vehicles:/usr/vehiclesAPI
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/vehiculos_db?schema=public"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: vehiculos_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
